trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: CredFile
    value: client_id
  - name: CredFileLibrary
    value: product-readiness.auth_pkce_powerbi.client_id
  - name: CredFileTenantID
    value: tenant_id
  - name: CredFileTenantIDLibrary
    value: product-readiness.auth_pkce_powerbi.tenant_id
  - name: CredFileURL
    value: url
  - name: CredFileURLLibrary
    value: product-readiness.auth_pkce_powerbi.url
  - name: CredFileTest
    value: appsettings.json
  - name: CredFileTestLibrary
    value: product-readiness.auth_pkce_powerbi.json
  - name: analysisProject
    value: Auth_PKCE_PowerBI

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: /OCSConnector

      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFileTenantID)
          fileLibrary: $(CredFileTenantIDLibrary)
          filePath: /OCSConnector

      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFileURL)
          fileLibrary: $(CredFileURLLibrary)
          filePath: /OCSConnector

      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFileTest)
          fileLibrary: $(CredFileTestLibrary)
          filePath: /OCSConnectorTest

      - script: |
          dir
          call vsdevcmd
          call msbuild -t:rebuild"
          call copy /y ".\OCSConnector\bin\Debug\OCSConnector.mez" "C:\Users\$(username)\Documents\Power BI Desktop\Custom Connectors"
        displayName: 'Build'

      - script: start cmd /c "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"
        displayName: 'Start test dependencies'

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
          workingDirectory: $(Build.SourcesDirectory)\OCSConnectorTest

      - script: |
          taskkill /F /IM PBIDesktop.exe
          taskkill /F /IM WinAppDriver.exe
        continueOnError: true
        displayName: 'Stop test processes'
        condition: succeededOrFailed()

      - template: '/miscellaneous/build_templates/analysis.yml@templates'
